#ifndef _TOKENS_
#define _TOKENS_

#define ID                  1
#define VOID                2
#define INT                 3
#define DOUBLE              4
#define BOOL                5
#define STRING_KW           6
#define CLASS               7
#define _NULL               8
#define FOR                 9
#define WHILE               10
#define IF                  11
#define ELSE                12
#define RETURN              13
#define BREAK               14
#define NEW                 15
#define THIS                16
#define NEWARRAY            17
#define PRINT               18
#define READINTEGER         19
#define READLINE            20
#define INTEGER             21
#define FLOAT               22
#define PLUS                23
#define MINUS               24
#define STAR                25
#define LESSTHAN            26
#define GREATERTHAN         27
#define LESSTHANEQUAL       28
#define GREATERTHANEQUAL    29
#define EQUAL               30
#define NOTEQUAL            31
#define AND                 32
#define OR                  33
#define STRING              34 
#define BOOLEAN             35
#define OPENBRACE           36
#define CLOSEBRACE          37 
#define OPENBRACKET         38 
#define CLOSEBRACKET        39
#define COMMA               40 
#define ASSIGN              41
#define SEMICOLON           42
#define OPENPARANTHESES     43
#define CLOSEPARANTHESES    44
#define IMPORT              45
#define LINE                46
#define FUNC                47
#define PLUSEQUAL           48
#define MINUSEQUAL          49
#define STAREQUAL           50
#define SLASHEQUAL          51
#define PLUSPLUS            52
#define MINUSMINUS          53
#define NOT                 54
#define DOT                 55
#define DIVISION            56
#define PERCENT             57

#endif
